// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToeLibary.Database;

#nullable disable

namespace TicTacToeLibary.Migrations
{
    [DbContext(typeof(TicTacToeDatabaseContext))]
    partial class TicTacToeDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TicTacToeLibary.Players.GameResult", b =>
                {
                    b.Property<int>("GameResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HumanPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameResultId");

                    b.HasIndex("HumanPlayerId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("TicTacToeLibary.Players.HumanPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TicTacToeLibary.Players.GameResult", b =>
                {
                    b.HasOne("TicTacToeLibary.Players.HumanPlayer", null)
                        .WithMany("GameResults")
                        .HasForeignKey("HumanPlayerId");
                });

            modelBuilder.Entity("TicTacToeLibary.Players.HumanPlayer", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
